language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js: 10

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn lint

notifications:
  email:
    on_success: never
on_failure: change